name: ContinuousIntegration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install frontend dependencies and run tests
        working-directory: ./front
        run: npm install && npm test -- --watch=false --code-coverage --browsers=ChromeHeadlessCI

      - name: Build and verify backend with Maven
        working-directory: ./back
        run: mvn verify

      - name: Commit and push coverage reports
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://github.com/Torus-Ortie/Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD.git
          git add -f ./front/coverage/bobapp/index.html
          git add -f ./back/target/site/jacoco/index.html
          git commit -m "Add coverage reports [skip ci]"
          git push https://github.com/Torus-Ortie/Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD.git HEAD:main

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=Torus-Ortie/Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD \
            -Dsonar.organization=Torus-Ortie \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}